apiVersion: apps/v1
kind: Deployment
metadata:
  name: alert-sink
  namespace: samma
  labels:
    app: alert-sink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alert-sink
  template:
    metadata:
      labels:
        app: alert-sink
    spec:
      containers:
        - name: vector
          image: timberio/vector:0.53.0-alpine
          volumeMounts:
            - name: config
              mountPath: /etc/vector
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
      volumes:
        - name: config
          configMap:
            name: alert-sink-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-sink-config
  namespace: samma
data:
  vector.yaml: |
    data_dir: /vector-data-dir

    sources:
      nats_alerts:
        type: nats
        url: "nats://nats.samma.svc.cluster.local:4222"
        subject: "samma.alerts.>"
        queue: "alert-sink"
        connection_name: "alert-sink"

    transforms:
      prepare_for_es:
        type: remap
        inputs:
          - nats_alerts
        source: |
          .@timestamp = now()

          # Parse the NATS message payload (JSON string from the SIEM)
          if is_string(.message) {
            parsed, err = parse_json(.message)
            if err == null {
              .rule = parsed.rule
              .event = parsed.event
              del(.message)
            }
          }

          # Determine ES index by alert severity
          severity = if exists(.rule.severity) {
            downcase(string!(.rule.severity))
          } else {
            "unknown"
          }
          .index_name = "samma-alerts-" + severity

    sinks:
      elasticsearch:
        type: elasticsearch
        inputs:
          - prepare_for_es
        endpoints:
          - "http://elasticsearch.samma.svc.cluster.local:9200"
        bulk:
          index: "{{ index_name }}"
        encoding:
          except_fields:
            - index_name
