apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: samma
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.4.0
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: admin
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: samma
          volumeMounts:
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: dashboard-provisioning
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: dashboards
              mountPath: /opt/grafana/dashboards
              readOnly: true
            - name: data
              mountPath: /var/lib/grafana
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 256Mi
      volumes:
        - name: datasources
          configMap:
            name: grafana-datasources
        - name: dashboard-provisioning
          configMap:
            name: grafana-dashboard-provisioning
        - name: dashboards
          configMap:
            name: grafana-dashboards
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: samma
data:
  elasticsearch.yaml: |
    apiVersion: 1
    datasources:
      - name: Elasticsearch - Alerts
        uid: samma-es-alerts
        type: elasticsearch
        access: proxy
        url: http://elasticsearch.samma.svc.cluster.local:9200
        database: "samma-alerts-*"
        isDefault: true
        jsonData:
          timeField: "@timestamp"
          esVersion: "8.12.0"
          logMessageField: ""
          logLevelField: "rule.severity"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: samma
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-provisioning
  namespace: samma
data:
  dashboards.yaml: |
    apiVersion: 1
    providers:
      - name: samma
        orgId: 1
        folder: Samma
        type: file
        disableDeletion: false
        updateIntervalSeconds: 30
        options:
          path: /opt/grafana/dashboards
          foldersFromFilesStructure: false
