apiVersion: apps/v1
kind: Deployment
metadata:
  name: siem
  namespace: samma
  labels:
    app: siem
spec:
  replicas: 1
  selector:
    matchLabels:
      app: siem
  template:
    metadata:
      labels:
        app: siem
    spec:
      containers:
        - name: siem
          image: sammascanner/siem:v0.1
          ports:
            - containerPort: 8080
          env:
            - name: SIEM_HTTP_PORT
              value: "8080"
            - name: SIEM_NATS_URL
              value: "nats://nats.samma.svc.cluster.local:4222"
            - name: SIEM_NATS_SUBSCRIBE
              value: "samma.logs.>"
            - name: SIEM_RULES_DIR
              value: "/app/rules"
          volumeMounts:
            - name: rules
              mountPath: /app/rules
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
      volumes:
        - name: rules
          configMap:
            name: siem-rules
---
apiVersion: v1
kind: Service
metadata:
  name: siem
  namespace: samma
spec:
  selector:
    app: siem
  ports:
    - port: 8080
      targetPort: 8080
